cifar10:
  learning_rate: 2e-3
  learning_scenario: supervised
  weight_decay: 2e-2
  ema: 0.999
  batch_size: 64
  max_steps: 1048576
  max_epochs: 2000
  gpus: 0
  label_smoothing: 0.001
  alpha: 1
  algo: mixup
  num_val: 10
  affix: fs_mixup
